services:
  - type: web
    name: topgrade-school
    runtime: python
    region: frankfurt        # Change to oregon (US) or singapore if preferred
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn topgrade_school.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"